Viewer for binary data - 2
mucommander/mucommander pull request #503
Opened 2021-09-02 01:30 UTC by hajdam

Continuation of pull request #246 - next step before introduction of binary editor to muCommander.

- Viewers and editors to use interfaces instead of abstract parent
- Passing by component instead of JScrollPane
- Switching between multiple viewers and multiple editors via menu bar
- Updated library of binary viewer

Before next steps, I though it would be better to see if this change will be acceptable. If I remember correctly, using tabs was not seen as a good idea, so I hope, that using menu might be more ok.

Hopefully I'll have time to continue on this sooner that two years later like the last time. :-I

2021-09-12 20:34 UTC, ahadas reviewed
Thanks for posting this. Just a few comments after a very partial review

2021-09-12 20:34 UTC, ahadas commented on mucommander-core/src/main/java/com/mucommander/ui/viewer/EditorFrame.java
> +        int count = EditorRegistrar.registerFileEditors(file, presenter, this);
how about renaming `count` to something more meaningful like numOfEditors?

2021-09-12 20:34 UTC, ahadas commented on mucommander-core/src/main/java/com/mucommander/ui/viewer/FilePresenter.java
> +    private JComponent component = null;
no need to initialize to null here

2021-09-26 22:02 UTC, ahadas requested changes
thanks for addressing the previous comments, I just completed reviewing everything. added relatively minor comments, it looks good overall

2021-09-27 07:55 UTC, hajdam commented on mucommander-viewer-binary/src/main/java/com/mucommander/viewer/binary/BinaryViewer.java
> +        codeCharacterCaseMenu = new JMenu("Code Character Case");
Well, I planned to do that once I'll also add binary editor so that there will be less duplicates. Same for registering shortcuts for actions.

2021-09-27 08:29 UTC, hajdam commented on mucommander-viewer-text/src/main/java/com/mucommander/viewer/text/TextViewer.java
> -        setRowHeaderView(show ? lineNumbersPanel : null);
My fault - it's something I forgot to revert when I had issue with line numbers not showing :-/

2021-09-27 08:29 UTC, hajdam commented on mucommander-viewer-binary/src/main/java/com/mucommander/viewer/binary/BinaryViewer.java
> +        // TODO
Eh, I forgot to make that TODO...

2021-09-27 14:22 UTC, ahadas approved these changes
thanks!

2021-09-27 14:22 UTC, ahadas commented on mucommander-viewer-binary/src/main/java/com/mucommander/viewer/binary/BinaryViewer.java
> +        codeCharacterCaseMenu = new JMenu("Code Character Case");
ack

2021-09-27 14:22 UTC, merged