Undo/redo for binary editor
mucommander/mucommander pull request #908
Opened 2023-04-19 20:33 UTC by hajdam

Added undo/redo for binary editor

2023-04-19 20:52 UTC, pskowronek requested changes
see my comments

2023-04-19 20:52 UTC, pskowronek commented on mucommander-viewer-binary/src/main/java/com/mucommander/viewer/binary/BinaryEditor.java
> +                        Logger.getLogger(BinaryEditor.class.getName())
Make it a final member of BinaryEditor?

2023-04-19 20:52 UTC, pskowronek commented on mucommander-viewer-binary/src/main/java/com/mucommander/viewer/binary/BinaryEditor.java
> +                    try {
Move the body to a new method that catches and logs the exception. This way you could simply do sth like this: `e -> doUndo` - a cleaner code, plus you would avoid code duplication (there's another occurrence of undo code below).

2023-04-19 20:52 UTC, pskowronek commented on mucommander-viewer-binary/src/main/java/com/mucommander/viewer/binary/BinaryEditor.java
> +                e -> {
the same for Redo

2023-04-20 17:34 UTC, pskowronek commented
Thanks for updates @hajdam, no more remarks from my side. @ahadas ?

2023-04-20 17:34 UTC, pskowronek approved these changes
looks good from my side.

2023-04-21 19:44 UTC, ahadas reviewed
@hajdam thanks, besides the minor comment inside can you please add a line about this in the [readme file](https://github.com/mucommander/mucommander/blob/master/package/readme.txt)?

2023-04-21 19:44 UTC, ahadas commented on mucommander-viewer-binary/src/main/java/com/mucommander/viewer/binary/BinaryEditor.java
> +            // here or when in #getActionName
it's ok here, this comment can be dropped

2023-04-21 21:57 UTC, pskowronek commented
> @hajdam thanks, besides the minor comment inside can you please add a line about this in the [readme file](https://github.com/mucommander/mucommander/blob/master/package/readme.txt)?

@hajdam the changes are good, but I guess @ahadas meant to add a note to either `New featues` or `Improvements' section?

2023-04-21 22:06 UTC, hajdam commented
> > @hajdam thanks, besides the minor comment inside can you please add a line about this in the [readme file](https://github.com/mucommander/mucommander/blob/master/package/readme.txt)?
> 
> @hajdam the changes are good, but I guess @ahadas meant to add a note to either `New featues` or `Improvements` section?

Oh, I didn't notice that section :-|

2023-04-22 06:43 UTC, ahadas approved these changes
thanks!

2023-04-22 06:43 UTC, merged

2023-04-23 22:36 UTC, pskowronek commented
@hajdam  any chance for Find/Search support in Binary Editor? :)

2023-04-24 11:19 UTC, hajdam commented
> @hajdam any chance for Find/Search support in Binary Editor? :)

I could copy find/search capability from standalone app, but as I understand it, binary viewer module should be kept in minimal form, because internal viewers/editors are not part of the core functionality in the muCommander.
Not sure how far it is allowed to be expanded... :-|

2023-04-24 17:01 UTC, pskowronek commented
I've just added additional search options and replace all to internal viewer/editor.
Probably it would be nice to have at least search for binary editor (a feature that is very helpful if binary editor is needed). @ahadas, any thoughts?

2023-04-26 17:34 UTC, pskowronek commented
Moved to discussion here: https://github.com/mucommander/mucommander/discussions/914

2023-07-08 18:18 UTC, ahadas commented
Version 1.3.0 that includes a fix for this issue [has been released](https://github.com/mucommander/mucommander/releases/tag/1.3.0-1)